import fs from "fs"

/**
 * The publishable key is generated by the backend at first boot and shared
 * via the mounted /shared volume. Resolve it at runtime so the storefront
 * image never has to be rebuilt when the key changes.
 */
let cached: string | null = null

export function getPublishableKey(): string {
  if (cached) return cached
  if (process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY) {
    cached = process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
    return cached
  }
  for (const p of ["/shared/publishable_key.txt", process.env.PUBLISHABLE_KEY_FILE]) {
    try {
      if (p && fs.existsSync(p)) {
        const v = fs.readFileSync(p, "utf-8").trim()
        if (v) {
          cached = v
          return cached
        }
      }
    } catch {
      /* ignore */
    }
  }
  return ""
}
